apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: random-todo-job
            env:
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-service.staging/todos"
